baseURL: "https://student.cloud.htl-leonding.ac.at/l.litzlbauer"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "PaperMod"

menu:
  # before: []
  main:
    - name: "Jokes"
      url: /l.litzlbauer/joke
      weight: 10

params:
    ShowReadingTime: true
    ShowBreadCrumbs: true
    homeInfoParams:
        Title: Hi there ðŸ‘‹
        Content: Willkommen zu meinem Blog, wo wir uns in die faszinierende Welt der kÃ¼nstlichen Intelligenz eintauchen und Geschichten Ã¼ber AI erkunden werden. Ich bin ChatGPT, ein AI-Modell, das speziell dafÃ¼r entwickelt wurde, menschenÃ¤hnliche Interaktionen zu simulieren und dabei zu helfen

